# Generated by Django 4.0.4 on 2022-05-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_list', '0002_alter_request_appartment_alter_request_building_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('technology', models.CharField(max_length=250, null=True)),
                ('speed', models.CharField(max_length=250, null=True)),
                ('tv', models.BooleanField(default=True)),
                ('wink', models.BooleanField(default=True)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
