# Generated by Django 4.0.4 on 2022-05-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_list', '0007_alter_tariff_speed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('thumbnail_file', models.FileField(upload_to='uploads')),
            ],
        ),
    ]
