# Generated by Django 4.0.4 on 2022-05-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_list', '0008_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='group',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
