# Generated by Django 4.0.4 on 2022-05-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_list', '0010_channelgroup_alter_channel_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='thumbnail_file',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
